# Generated by Django 3.2.23 on 2023-12-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_alter_post_posted_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
    ]
