# Generated by Django 3.2.23 on 2023-12-21 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_remove_post_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img_files',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
