# Generated by Django 3.2.23 on 2023-12-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_auto_20231221_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_imgs',
        ),
        migrations.AddField(
            model_name='post',
            name='posted_imgs',
            field=models.FileField(blank=True, upload_to='users_images'),
        ),
        migrations.DeleteModel(
            name='Img_Files',
        ),
    ]
