# Generated by Django 3.2.23 on 2023-12-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0005_auto_20231221_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='users_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_imgs',
        ),
        migrations.AddField(
            model_name='post',
            name='posted_imgs',
            field=models.ManyToManyField(blank=True, to='Gallery.Img_Files'),
        ),
    ]
