# Generated by Django 3.2.23 on 2023-12-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0006_auto_20231221_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_files',
            name='img',
            field=models.FileField(upload_to='Gallery/users_images'),
        ),
    ]
